services:
  gateway:
    build: ./gateway
    ports:
      - "127.0.0.1:3000:80"
    depends_on:
      - interface
      - api-dados
      - auth
    networks:
      - app-network

  api-dados:
    build:
      context: .
      dockerfile: api-dados/Dockerfile
    expose:
      - "3001"
    environment:
      - MONGO_URL=mongodb://mongodb_api:27017/recursos_educativos
      - JWT_SECRET=jcr_secret_2026
      - COOKIE_NAME=token
      - SWAGGER_URL=http://localhost:3000/api-dados
      - INTERFACE_URL=http://interface:3000
      - INTERNAL_NEWS_SECRET=jcr_internal_news_2026
    depends_on:
      - mongodb_api
    volumes:
      - api_dados_uploads:/app/uploads
    networks:
      - app-network

  auth:
    build: ./auth
    expose:
      - "2623"
    environment:
      - MONGO_URL=mongodb://mongodb_api:27017/recursos_educativos
      - PORT=2623
      - JWT_SECRET=jcr_secret_2026
      - COOKIE_NAME=token
      - SWAGGER_URL=http://localhost:3000/auth-service
      - INTERFACE_URL=http://interface:3000
      - INTERNAL_NEWS_SECRET=jcr_internal_news_2026
    depends_on:
      - mongodb_api
    networks:
      - app-network

  interface:
    build: ./interface
    expose:
      - "3000"
    environment:
      - PORT=3000
      - API_URL=http://api-dados:3001
      - AUTH_URL=http://auth:2623/users
      - COOKIE_NAME=token
      - JWT_SECRET=jcr_secret_2026
      - INTERNAL_NEWS_SECRET=jcr_internal_news_2026
    depends_on:
      - api-dados
      - auth
    networks:
      - app-network

  mongodb_api:
    build:
      context: ./api-dados
      dockerfile: Dockerfile.mongo
    expose:
      - "27017"
    volumes:
      - mongodb_api_data:/data/db
      - ./api-dados/mongo_init:/docker-entrypoint-initdb.d
    networks:
      - app-network

volumes:
  mongodb_api_data:
  api_dados_uploads:

networks:
  app-network:
    driver: bridge
