server {
    listen 80;
    server_name _;

    client_max_body_size 100m;

    location = /api-dados {
        return 302 /api-dados/;
    }

    location = /api-dados/docs {
        return 302 /api-dados/docs/;
    }

    location = /auth-service {
        return 302 /auth-service/;
    }

    location = /auth-service/docs {
        return 302 /auth-service/docs/;
    }

    location /api-dados/ {
        proxy_pass http://api-dados:3001/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /auth-service/ {
        proxy_pass http://auth:2623/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
        proxy_pass http://interface:3000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
